import type {Metadata} from "next";
import {AppRouterCacheProvider} from "@mui/material-nextjs/v16-appRouter";
import {Roboto} from "next/font/google";
import {ThemeProvider} from "@mui/material/styles";
import theme from "@/app/theme";

const roboto = Roboto({
    weight: ['300', '400', '500', '700'],
    subsets: ["latin"],
    display: "swap",
    variable: '--font-roboto'
});

import "./globals.css";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html
            lang="hu"
            className={`${roboto.variable} h-full`}
        >
        <body className="min-h-full flex flex-col">
        <AppRouterCacheProvider>
            {children}
        </AppRouterCacheProvider>
        </body>
        </html>
    );
}
